models/topic.py
from .user import User
from .pymongodb import Mongodb
import json


"""
class Topic(Model):


    def __init__(self, form):
        self.id = None
        self.views = 0
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.ct = int(time.time())
        self.ut = self.ct
        self.user_id = form.get('user_id', '')
        self.board_id = int(form.get('board_id', -1))


    @classmethod
    def get_views(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        rs = Reply.find_all(topic_id = self.id)
        return rs

    def user(self):
        u = User.find_by(id=self.user_id)
        return u
"""
class Cache(object):
    def get(self, key):
        pass

    def set(self, key, value):
        pass

class RedisCache(Cache):
    import redis
    redis_db = redis.StrictRedis(host='localhost', port=6379, db=0)

    def set(self, key, value):
        return self.__class__.redis_db.set(key, value)

    def get(self, key):
        return self.__class__.redis_db.get(key)


class Topic(Mongodb):
    __fields__ = Mongodb.__fields__ + [
        ('content', str, ''),
        ('title', str, ''),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('views', int, 0),
    ]

    should_update_all = True
    redis_cache = RedisCache()
    def to_json(self):
        d = dict()
        for k in Topic.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self, key)
        return json.dumps(d)

    @classmethod
    def from_json(cls, j):
        d = json.loads(j)
        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        return Topic.all()

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def save(self):
        super(Topic, self).save()
        self.__class__.should_update_all = True

    @classmethod
    def cache_all(cls):
        if cls.should_update_all:
            cls.redis_cache.set('topic_all', json.dumps([i.to_json() for i in cls.all_delay()]))
            cls.should_update_all = False
        j = json.loads(cls.redis_cache.get('topic_all').decode('utf-8'))
        j = [cls.from_json(i) for i in j]
        return j


    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m


    def user(self):
        u = User.find(id=self.user_id)
        return u

    @classmethod
    def get_views(cls, id):
        m = cls.find_one(id=id)
        m.views += 1
        m.save()
        return m

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory
)

main = Blueprint('reply', __name__)

from models.reply import Reply
from .index import current_user


@main.route('/add', methods=["POST"])
def add():
    form = request.form
    reply = Reply.new(form)
    u = current_user()
    reply.set_user_id(u.id)
    return redirect(url_for('topic.detail', id=reply.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
)

main = Blueprint('topic', __name__)

from .index import current_user
from models.topic import Topic
from models.board import Board
import uuid

csrf_tokens = dict()

@main.route("/")
def index():
    board_id = int(request.args.get("board_id", -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)
    token = str(uuid.uuid4())
    u = current_user()
    csrf_tokens['token'] = u.id
    all_board = Board.all()
    return render_template("topic/index.html", ms=ms,all_board=all_board, token=token)

@main.route("/<int:id>")
def detail(id):
    m = Topic.get_views(id)
    return render_template("/topic/detail.html", topic=m)


@main.route("/new")
def new():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        bs = Board.all()
        return render_template("topic/new.html", bs=bs)


@main.route("/add", methods=["POST"])
def add():
    u = current_user()
    if u is None:
        return redirect(url_for("index.index"))
    else:
        form = request.form
        t = Topic.new(form, user_id=u.id)
        return redirect(url_for(".detail", id=t.id))

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
     <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="header topic_header">
                    <span class="topic_full_title">
                        {{ topic.title }}
                    </span>
                </div>
                <div class="changes">
                    <span>发布于2天前</span>
                    <span>作者</span>
                    <span>{{ topic.views }} 次浏览</span>
                    <span>来自 问答</span>
                </div>
                <div class="inner topic">
                    <div class="topic_full_title">
                        <div class="markdown-text">
                            {{ topic.content }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel">
                <div class="header">
                  <span class="col_fade">{{ topic.replies() | count }} 回复</span>
                </div>
                {% for reply in topic.replies() %}
                    <div class="cell reply_area reply_item" reply_id="{{ reply.id }}" reply_to_id="" id="{{ reply.id }}">
                            <div class="author_content">
                                <a href="#" class="user_avatar">
                                    <img src="{{ '/uploads/' + reply.user().user_image + '?v=4&amp;s=120'}}" title="{{ reply.user().username }}">
                                </a>
                                <div class="user_info">
                                    <a class="dark reply_author" href="#">{{ reply.user().username }}</a>
                                    <a class="reply_time" href="{{ '#' + reply.id|string }}">{{ loop.index }}楼•{{ reply.push_time() }}</a>
                                </div>
                            </div>
                            <div class="reply_content from-Lizhooh">
                        <div class="markdown-text">
                            {{ reply.content }}
                        </div>
                    </div>
                    <div class="clearfix">
                        <div class="reply2_area">
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <form action="{{ url_for('reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
     <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id='main'>
        <div id='sidebar'>
            <div class='panel'>
                <div class='inner'>
                    <a href="/topic/new" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic" class="topic-tab current-tab">全部</a>
                    {% for board in all_board %}
                        <a href="/topic?board_id={{ board.id }}" class="topic-tab">{{ board.title }}</a>
                    {% endfor %}
                </div>
                <div class="inner no-padding">
                    <div id="topic_list">
                        {% for t in ms %}
                            <div class="cell">
                            <a class="user_avatar pull-left">
                                <img src="{{ '/uploads/' + t.user().user_image + '?v=3amp;s=120' }}" title="{{ t.user().username }}"/>
                            </a>
                                <div class="topic_title_wrapper">
                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class="span9" id="title"
                                      name="title" rows="1" placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择板块：</span>
                            <select name="board_id" id="board" required>
                                <option value="">请选择</option>
                                    {% for b in bs %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endfor %}
                            </select>
                            <div class="markdown_editor in_editor">
                                <div class="markdown_in_editor">
                                    <textarea class="editor" name="content" rows="20" placeholder="文章支持Markdown 语法， 请注意标记代码"></textarea>
                                    <div class="editor_buttons">
                                        <input type="submit" class="span-primary submit_btn" data-loading-text="提交中" value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>